version: "3.7"

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=sample
      - MYSQL_DATABASE=sampleDB
      - MYSQL_USER=sampleUser
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
